/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register.presentation.view;

import Register.Application;
import Register.Entities.Grupo;
import Register.Entities.Profesor;
import Register.presentation.controller.GrupoController;
import Register.presentation.model.GrupoModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabio
 */
public class GrupoView extends javax.swing.JDialog implements java.util.Observer{
    GrupoController controller;
    GrupoModel model;
    /**
     * Creates new form GrupoView
     */
    public GrupoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //
        List<Profesor> profes = Application.Model.search_PRO("",0);
        for(Profesor p : profes){
            this.profeFld.addItem(p.getNombre());
        }
        //
    }
    
    public void setController(GrupoController controller){
        this.controller=controller;
    }
    public void setModel(GrupoModel model){
        this.model=model;
         model.addObserver(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroLabel = new javax.swing.JLabel();
        numeroFld = new javax.swing.JTextField();
        horarioLabel = new javax.swing.JLabel();
        profeLabel = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        diaFld1 = new javax.swing.JComboBox<>();
        diaFld2 = new javax.swing.JComboBox<>();
        inicioFld = new javax.swing.JComboBox<>();
        inicioLabel = new javax.swing.JLabel();
        finLabel = new javax.swing.JLabel();
        finFld = new javax.swing.JComboBox<>();
        profeFld = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Grupo");

        numeroLabel.setText("Numero:");

        numeroFld.setColumns(5);

        horarioLabel.setText("Dias:");

        profeLabel.setText("Profesor:");
        profeLabel.setName(""); // NOI18N

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        diaFld1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        diaFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFld1ActionPerformed(evt);
            }
        });

        diaFld2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));

        inicioFld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm" }));

        inicioLabel.setText("Hora Inicio:");

        finLabel.setText("Hora Fin:");

        finFld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(finLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(inicioLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inicioFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroLabel)
                            .addComponent(horarioLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diaFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(diaFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numeroFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profeLabel)
                        .addGap(26, 26, 26)
                        .addComponent(profeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelarBtn)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioLabel)
                    .addComponent(diaFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicioLabel)
                    .addComponent(inicioFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finLabel)
                    .addComponent(finFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profeLabel)
                    .addComponent(profeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void diaFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaFld1ActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.controller.guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrupoView dialog = new GrupoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void update(java.util.Observable updatedModel,Object parametros){
       
       if (parametros != GrupoModel.GRUPO_CURRENT) return;
       
       Grupo grupoCurrent = model.getGrupoCurrent();
        
       //this.numeroFld.setEnabled(model.getModo()==Application.MODO_AGREGAR);
              
       Integer numero=grupoCurrent.getNumeroGrupo();
       if(numero==0)numeroFld.setText("");
       else numeroFld.setText(numero.toString());
       
       String dia1="";
       if(grupoCurrent.isLunes()){
               dia1="Lunes";
               diaFld1.setSelectedItem(dia1);
       }else if(grupoCurrent.isMartes()){
               dia1="Martes";
               diaFld1.setSelectedItem(dia1);
       }else if(grupoCurrent.isMiercoles()){
               dia1="Miercoles";
               diaFld1.setSelectedItem(dia1);
       }else if(grupoCurrent.isJueves()){
               dia1="Jueves";
               diaFld1.setSelectedItem(dia1);
       }else if(grupoCurrent.isViernes()){
               dia1="Viernes";
               diaFld1.setSelectedItem(dia1);
       }else diaFld1.setSelectedIndex(0);
       
       
       if(grupoCurrent.isLunes() && !(dia1.equals("Lunes")))
            diaFld2.setSelectedItem("Lunes");
       else if(grupoCurrent.isMartes() && !(dia1.equals("Martes")))
            diaFld2.setSelectedItem("Martes");
       else if(grupoCurrent.isMiercoles() && !(dia1.equals("Miercoles")))
            diaFld2.setSelectedItem("Miercoles");
       else if(grupoCurrent.isJueves() && !(dia1.equals("Jueves")))
            diaFld2.setSelectedItem("Jueves");
       else if(grupoCurrent.isViernes() && !(dia1.equals("Viernes")))
            diaFld2.setSelectedItem("Viernes");
       else diaFld2.setSelectedIndex(0);
       
       if(!grupoCurrent.getHoraInicio().equals(""))
            inicioFld.setSelectedItem(grupoCurrent.getHoraInicio());
       else inicioFld.setSelectedIndex(0);
       if(!grupoCurrent.getHoraFin().equals(""))
            finFld.setSelectedItem(grupoCurrent.getHoraFin());
       else finFld.setSelectedIndex(0);
       if(!grupoCurrent.getProfesor().getNombre().equals(""))       
            profeFld.setSelectedItem(grupoCurrent.getProfesor().getNombre());
       else profeFld.setSelectedIndex(0);
               
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelarBtn;
    public javax.swing.JComboBox<String> diaFld1;
    public javax.swing.JComboBox<String> diaFld2;
    public javax.swing.JComboBox<String> finFld;
    public javax.swing.JLabel finLabel;
    public javax.swing.JButton guardarBtn;
    public javax.swing.JLabel horarioLabel;
    public javax.swing.JComboBox<String> inicioFld;
    public javax.swing.JLabel inicioLabel;
    public javax.swing.JTextField numeroFld;
    public javax.swing.JLabel numeroLabel;
    public javax.swing.JComboBox<String> profeFld;
    public javax.swing.JLabel profeLabel;
    // End of variables declaration//GEN-END:variables
}
