/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register.presentation.view;

import Register.presentation.controller.MenuController;

/**
 *
 * @author Fabio
 */
public class MenuView extends javax.swing.JFrame {

    MenuController controller;
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    public void setController(MenuController controller){
        this.controller=controller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        grupo1 = new javax.swing.ButtonGroup();
        mantenCursosBtn = new javax.swing.JToggleButton();
        mantenCarrerasBtn = new javax.swing.JToggleButton();
        mantenProfesBtn = new javax.swing.JToggleButton();
        ofertaAcadBtn = new javax.swing.JToggleButton();
        mantenCiclosBtn = new javax.swing.JToggleButton();
        mantenEstBtn = new javax.swing.JToggleButton();
        regNotasBtn = new javax.swing.JToggleButton();
        consultHistBtn = new javax.swing.JToggleButton();
        menuLabel = new javax.swing.JLabel();
        SeguridadBtn = new javax.swing.JToggleButton();
        LogoutBtn = new javax.swing.JToggleButton();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Matricula");

        grupo1.add(mantenCursosBtn);
        mantenCursosBtn.setText("Mantenimiento de Cursos");
        mantenCursosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenCursosBtnActionPerformed(evt);
            }
        });

        grupo1.add(mantenCarrerasBtn);
        mantenCarrerasBtn.setText("Mantenimiento de Carreras");
        mantenCarrerasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenCarrerasBtnActionPerformed(evt);
            }
        });

        grupo1.add(mantenProfesBtn);
        mantenProfesBtn.setText("Mantenimiento de Profesores");
        mantenProfesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenProfesBtnActionPerformed(evt);
            }
        });

        grupo1.add(ofertaAcadBtn);
        ofertaAcadBtn.setText("Oferta Academica");
        ofertaAcadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaAcadBtnActionPerformed(evt);
            }
        });

        grupo1.add(mantenCiclosBtn);
        mantenCiclosBtn.setText("Mantenimiento de Ciclos");
        mantenCiclosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenCiclosBtnActionPerformed(evt);
            }
        });

        grupo1.add(mantenEstBtn);
        mantenEstBtn.setText("Mantenimiento de Estudiantes");
        mantenEstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenEstBtnActionPerformed(evt);
            }
        });

        grupo1.add(regNotasBtn);
        regNotasBtn.setText("Registro de Notas");
        regNotasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNotasBtnActionPerformed(evt);
            }
        });

        grupo1.add(consultHistBtn);
        consultHistBtn.setText("Consulta de Historial");
        consultHistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultHistBtnActionPerformed(evt);
            }
        });

        menuLabel.setText("MENU PRINCIPAL");

        grupo1.add(SeguridadBtn);
        SeguridadBtn.setText("Seguridad");
        SeguridadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadBtnActionPerformed(evt);
            }
        });

        grupo1.add(LogoutBtn);
        LogoutBtn.setText("Cerrar Sesión");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(menuLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mantenEstBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mantenProfesBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mantenCarrerasBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mantenCiclosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ofertaAcadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regNotasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultHistBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mantenCursosBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeguridadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(menuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenCursosBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenCarrerasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenProfesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenEstBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenCiclosBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ofertaAcadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regNotasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultHistBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutBtn)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void mantenCursosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenCursosBtnActionPerformed
        this.controller.consultarOpcion(1);
    }//GEN-LAST:event_mantenCursosBtnActionPerformed

    private void mantenCarrerasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenCarrerasBtnActionPerformed
        this.controller.consultarOpcion(2);
    }//GEN-LAST:event_mantenCarrerasBtnActionPerformed

    private void mantenProfesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenProfesBtnActionPerformed
        this.controller.consultarOpcion(3);
    }//GEN-LAST:event_mantenProfesBtnActionPerformed

    private void mantenEstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenEstBtnActionPerformed
        this.controller.consultarOpcion(4);
    }//GEN-LAST:event_mantenEstBtnActionPerformed

    private void mantenCiclosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenCiclosBtnActionPerformed
        this.controller.consultarOpcion(5);
    }//GEN-LAST:event_mantenCiclosBtnActionPerformed

    private void ofertaAcadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaAcadBtnActionPerformed
        this.controller.consultarOpcion(6);
    }//GEN-LAST:event_ofertaAcadBtnActionPerformed

    private void regNotasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNotasBtnActionPerformed
        this.controller.consultarOpcion(7);
    }//GEN-LAST:event_regNotasBtnActionPerformed

    private void consultHistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultHistBtnActionPerformed
        this.controller.consultarOpcion(8);
    }//GEN-LAST:event_consultHistBtnActionPerformed

    private void SeguridadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadBtnActionPerformed
        this.controller.consultarOpcion(9);
    }//GEN-LAST:event_SeguridadBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        this.controller.consultarOpcion(10);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton LogoutBtn;
    public javax.swing.JToggleButton SeguridadBtn;
    public javax.swing.JToggleButton consultHistBtn;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JToggleButton mantenCarrerasBtn;
    public javax.swing.JToggleButton mantenCiclosBtn;
    public javax.swing.JToggleButton mantenCursosBtn;
    public javax.swing.JToggleButton mantenEstBtn;
    public javax.swing.JToggleButton mantenProfesBtn;
    public javax.swing.JLabel menuLabel;
    public javax.swing.JToggleButton ofertaAcadBtn;
    public javax.swing.JToggleButton regNotasBtn;
    // End of variables declaration//GEN-END:variables
}
